Add app: Job Manager
t9k/apps pull request #20
Opened 2024-07-12 08:44 UTC by tswangdi

2024-07-13 11:02 UTC, ppkube requested changes

2024-07-13 11:02 UTC, ppkube commented on user-console/job-manager/configs/v0_1_1.yaml
> +  serviceAccount: managed-project-sa
这个默认不需要修改吧？

2024-07-15 01:56 UTC, tswangdi commented on user-console/job-manager/chart/README.md
> +    home: "https://home.example.t9kcloud.cn"
这里是 helm chart 的默认设置

用户在 User Console 上的默认设置写在 configs/0_1_1.yaml 中了，其中这些问题都已解决

下面两个 conversation 与此相同

2024-07-15 01:57 UTC, tswangdi commented on user-console/job-manager/chart/README.md
> +    gpu: ["nvidia.com/gpu.shared", "nvidia.com/gpu"]
用户需要在创建 Job 时候选择 GPU，目前是通过 ConfigMap 传递给 Web 的。这里给用户添加 GPU 种类的方法

2024-07-15 02:03 UTC, tswangdi commented on user-console/job-manager/configs/v0_1_1.yaml
> +  serviceAccount: managed-project-sa
镜像也可以不需要修改，我也一起从这个文件去掉吧

我们分为 Helm Default Values 和 App Default Values 两个层面的默认配置：Helm Default Values 中包含最全的配置信息；App Default Values 是前端直接展示给用户，需要用户填写的配置信息。这里这个文件是后一种，这里去掉的配置在 Helm Default Values 中全部存在

2024-07-15 07:54 UTC, ppkube approved these changes

2024-07-15 07:54 UTC, merged